name: Publish to Github

on: 
  push:
    branches: 
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run build 
      run: ./gradlew test --info
    - name: Echo
      env: 
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: echo $GITHUB_ACTOR $GITHUB_TOKEN
    - name: Echo
      env: 
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      run: ./gradlew publish --info
